// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(MarketWizardContext))]
    partial class MarketWizardContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.Persistence.Entities.CronJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Gainers")
                        .HasColumnType("text");

                    b.Property<string>("IndicePerfomance")
                        .HasColumnType("text");

                    b.Property<string>("Losers")
                        .HasColumnType("text");

                    b.Property<string>("SectorPerformance")
                        .HasColumnType("text");

                    b.Property<string>("TopIndustries")
                        .HasColumnType("text");

                    b.Property<string>("TopNews")
                        .HasColumnType("text");

                    b.Property<string>("WorstIndustries")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CronJobs");
                });
#pragma warning restore 612, 618
        }
    }
}
